SovereignWorldbuilding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('homepage/', include('SovereignWebsite.urls')),
    url('worldbuilder/p/', include('Project.urls')),
    url('worldbuilder/p/', include('ItemList.urls')),
    url('worldbuilder/p/', include('Pantheon.urls')),
    url('worldbuilder/p/', include('Dungeon.urls')),
    url('worldbuilder/p/', include('Campaign.urls')),
    url('worldbuilder/p/', include('World.urls')),
    url('thelodge/', include('theLodge.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

World/urls.py
from django.urls import path

from World.views import universe_detail, universe_index, universe_create, universe_update, universe_delete
from World.views import region_detail, region_create, region_update, region_delete
from World.views import area_detail, area_create, area_update, area_delete
from World.views import city_detail, city_create, city_update, city_delete
from World.views import cityquarter_detail, cityquarter_create, cityquarter_update, cityquarter_delete
from World.views import citydemographics_create, citydemographics_delete
from World.views import location_detail, location_create, location_update, location_delete
from World.views import locationloot_create, locationloot_delete
from World.views import worldencounter_detail, worldencounter_create, worldencounter_update, worldencounter_delete
from World.views import worldencounterloot_create, worldencounterloot_delete

from World.views import empire_detail, empire_create, empire_update, empire_delete
from World.views import faction_detail, faction_create, faction_update, faction_delete
from World.views import npc_detail, npc_create, npc_update, npc_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/u/<str:name>/', universe_detail, name="universe-detail"),
	path('<int:in_project>/u/<str:name>/index/', universe_index, name="universe-index"),
	path('<int:in_project>/r/<str:name>/', region_detail, name="region-detail"),
	path('<int:in_project>/a/<str:name>/', area_detail, name="area-detail"),
	path('<int:in_project>/ct/<str:name>/', city_detail, name="city-detail"),
	path('<int:in_project>/cq/<str:name>/', cityquarter_detail, name="cityquarter-detail"),
	path('<int:in_project>/l/<str:name>/', location_detail, name="location-detail"),
	path('<int:in_project>/we/<str:title>/', worldencounter_detail, name="worldencounter-detail"),
	path('<int:in_project>/e/<str:name>/', empire_detail, name="empire-detail"),
	path('<int:in_project>/f/<str:name>/', faction_detail, name="faction-detail"),
	path('<int:in_project>/n/<str:name>/', npc_detail, name="npc-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Universes
	path('<int:in_project>/u/create/new/', universe_create, name="universe-create"),
	path('<int:in_project>/u/<str:name>/update/', universe_update, name="universe-update"),
	path('<int:in_project>/u/<str:name>/delete/', universe_delete, name="universe-delete"),

	# Regions
	path('<int:in_project>/u/<str:in_universe>/r/create/new/', region_create, name="region-create"),
	path('<int:in_project>/r/<str:name>/update/', region_update, name="region-update"),
	path('<int:in_project>/r/<str:name>/delete/', region_delete, name="region-delete"),

	# Areas
	path('<int:in_project>/r/<str:in_region>/a/create/new/', area_create, name="area-create"),
	path('<int:in_project>/a/<str:name>/update/', area_update, name="area-update"),
	path('<int:in_project>/a/<str:name>/delete/', area_delete, name="area-delete"),

	# Cities
	path('<int:in_project>/r/<str:in_region>/ct/create/new/', city_create, name="city-create"),
	path('<int:in_project>/ct/<str:name>/update/', city_update, name="city-update"),
	path('<int:in_project>/ct/<str:name>/delete/', city_delete, name="city-delete"),

	# City Quarters
	path('<int:in_project>/c/<str:in_city>/cq/create/new/', cityquarter_create, name="cityquarter-create"),
	path('<int:in_project>/cq/<str:name>/update/', cityquarter_update, name="cityquarter-update"),
	path('<int:in_project>/cq/<str:name>/delete/', cityquarter_delete, name="cityquarter-delete"),

	# City Demographics
	path('<int:in_project>/ct/<str:in_city>/ctd/create/new/', citydemographics_create, name="citydemographics-create"),
	path('<int:in_project>/ctd/<int:pk>/delete/', citydemographics_delete, name="citydemographics-delete"),

	# Locations
	path('<int:in_project>/a/<str:in_area>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/cq/<str:in_cityquarter>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/l/<str:name>/delete/', location_delete, name="location-delete"),

	# Location Loot
	path('<int:in_project>/l/<str:in_location>/ll/create/new/', locationloot_create, name="locationloot-create"),
	path('<int:in_project>/ll/<int:pk>/delete/', locationloot_delete, name="locationloot-delete"),

	# World Encounter
	path('<int:in_project>/rm/<str:in_dungeon_room>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/l/<str:in_location>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/we/<str:title>/update/', worldencounter_update, name="worldencounter-update"),
	path('<int:in_project>/we/<str:title>/delete/', worldencounter_delete, name="worldencounter-delete"),

	# World Encounter Loot
	path('<int:in_project>/we/<str:in_worldencounter>/wel/create/new/', worldencounterloot_create, name="worldencounterloot-create"),
	path('<int:in_project>/wel/<int:pk>/delete/', worldencounterloot_delete, name="worldencounterloot-delete"),

	# Empires
	path('<int:in_project>/u/<str:in_universe>/e/create/new/', empire_create, name="empire-create"),
	path('<int:in_project>/e/<str:name>/update/', empire_update, name="empire-update"),
	path('<int:in_project>/e/<str:name>/delete/', empire_delete, name="empire-delete"),

	# Factions
	path('<int:in_project>/u/<str:in_universe>/f/create/new/', faction_create, name="faction-create"),
	path('<int:in_project>/f/<str:name>/update/', faction_update, name="faction-update"),
	path('<int:in_project>/f/<str:name>/delete/', faction_delete, name="faction-delete"),

	# NPCs
	path('<int:in_project>/u/<str:in_universe>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/u/<str:in_universe>/f/<str:in_faction>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/f/<str:in_faction>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/n/<str:name>/delete/', npc_delete, name="npc-delete"),
]

World/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

from ItemList.models import Item
from Pantheon.models import God
from Project.models import Project

class Universe(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	description = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('universe-detail', args=[str(self.in_project.id), str(self.name)])

	def get_absolute_index_url(self):
		return reverse('universe-index', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Region(models.Model):
	name = models.CharField(max_length=125)
	landscape = models.URLField(max_length=255, blank=True, null=True,
					help_text="Provide a URL to an image file.")

	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey(Universe, on_delete=models.CASCADE, blank=True, null=True)

	BIOMES = (
		('Dr', 'Dry'),
		('Tr', 'Tropical'),
		('Te', 'Temperate'),
		('Co', 'Continental'),
		('Po', 'Polar'),
	)
	biome = models.CharField(max_length=2, choices=BIOMES, blank=True, null=True)

	description = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('region-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Area(models.Model):
	name = models.CharField(max_length=125)
	landscape = models.URLField(max_length=255, blank=True, null=True,
					help_text="Provide a URL to an image file.")

	area_type = models.CharField(max_length=255, blank=True, null=True)

	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_region = models.ForeignKey(Region, on_delete=models.CASCADE)

	factions = models.ManyToManyField('Faction', blank=True)

	description = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('area-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class City(models.Model):
	name = models.CharField(max_length=125)
	landscape = models.URLField(max_length=255, blank=True, null=True,
					help_text="Provide a URL to an image file.")

	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_region = models.ForeignKey(Region, on_delete=models.CASCADE)
	population = models.CharField(max_length=10, blank=True, null=True)

	description = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(blank=True, null=True)

	class Meta:
		verbose_name_plural = "Cities"
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('city-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class CityQuarter(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_city = models.ForeignKey(City, on_delete=models.CASCADE)

	factions = models.ManyToManyField('Faction', blank=True)

	description = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(blank=True, null=True)

	class Meta:
		verbose_name_plural = 'City Quarters'
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('cityquarter-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Location(models.Model):
	name = models.CharField(max_length=125)
	landscape = models.URLField(max_length=255, blank=True, null=True,
					help_text="Provide a URL to an image file..")

	location_type = models.CharField(max_length=125, blank=True, null=True)

	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_area = models.ForeignKey(Area, on_delete=models.CASCADE, blank=True, null=True)
	in_cityquarter = models.ForeignKey(CityQuarter, on_delete=models.CASCADE, blank=True, null=True)

	description = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(blank=True, null=True)

	NPCs = models.ManyToManyField('NPC', blank=True)

	exit_points = models.ManyToManyField('Location', blank=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('location-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class LocationLoot(models.Model):
	name = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_location = models.ForeignKey(Location, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "Location Loot"
		order_with_respect_to = 'name'

	def __str__(self):
		return self.name.name

class WorldEncounter(models.Model):
	title = models.CharField(max_length=125)
	encounter_num = models.IntegerField(blank=True, null=True)

	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_location = models.ForeignKey(Location, on_delete=models.CASCADE, blank=True, null=True)
	in_dungeon_room = models.ForeignKey('Dungeon.Room', on_delete=models.CASCADE, blank=True, null=True)

	ENCOUNTER_TYPES = (
		('gbe', 'Grid-based'),
		('totme', 'Theater-of-the-Mind'),
		('lbe', 'Lore-based'),
	)
	encounter_type = models.CharField(max_length=5, choices=ENCOUNTER_TYPES, blank=True, null=True)

	dramatic_question = models.CharField(max_length=255, blank=True, null=True)
	summary = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(blank=True, null=True)

	involved_npcs = models.ManyToManyField('NPC', blank=True)

	class Meta:
		ordering = ['encounter_num']

	def get_absolute_url(self):
		return reverse('worldencounter-detail', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class WorldEncounterLoot(models.Model):
	name = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_worldencounter = models.ForeignKey(
			WorldEncounter, on_delete=models.CASCADE
		)

	class Meta:
		verbose_name_plural = "World Encounter Loot"
		order_with_respect_to = 'name'

	def __str__(self):
		return self.name.name

class Empire(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey(Universe, on_delete=models.CASCADE)

	description = models.TextField(blank=True, null=True)

	regions = models.ManyToManyField('Region', blank=True)

	faiths = models.ManyToManyField(God, blank=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('empire-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Faction(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey(Universe, on_delete=models.CASCADE)
	faction_role = models.CharField(max_length=255, blank=True, null=True)

	ALIGNMENTS = (
		('LG', 'Lawful/Good'),
		('NG', 'Neutral/Good'),
		('CG', 'Chaotic/Good'),
		('LN', 'Lawful/Neutral'),
		('N', 'True Neutral'),
		('CN', 'Chaotic/Neutral'),
		('CE', 'Chaotic/Evil'),
		('NE', 'Neutral/Evil'),
		('LE', 'Lawful/Evil'),
	)

	alignment = models.CharField(max_length=2, choices=ALIGNMENTS, blank=True, null=True)
	faiths = models.ManyToManyField(God, blank=True)

	description = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('faction-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class NPC(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey(Universe, on_delete=models.CASCADE)
	in_faction = models.ForeignKey('Faction', on_delete=models.CASCADE, blank=True, null=True, related_name="faction")
	leader_of = models.ForeignKey('Faction', on_delete=models.CASCADE, blank=True, null=True, related_name="leader")
	portrait = models.URLField(max_length=255, blank=True, null=True,
				help_text="Provide a URL to an image file.")

	ALIGNMENTS = (
		('LG', 'Lawful/Good'),
		('NG', 'Neutral/Good'),
		('CG', 'Chaotic/Good'),
		('LN', 'Lawful/Neutral'),
		('N', 'True Neutral'),
		('CN', 'Chaotic/Neutral'),
		('LE', 'Lawful/Evil'),
		('NE', 'Neutral/Evil'),
		('CE', 'Chaotic/Evil'),
	)

	alignment = models.CharField(max_length=2, choices=ALIGNMENTS, blank=True, null=True)
	faiths = models.ManyToManyField(God, blank=True)

	description = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('npc-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Demographics(models.Model):
	race = models.CharField(max_length=125)
	percent = models.IntegerField()

	class Meta:
		abstract = True

class CityDemographics(Demographics):
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_city = models.ForeignKey(City, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'City Demographics'
		ordering = ('-percent', )

	def __str__(self):
		return self.race

World/templates/World/area_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ area }}"?</p>
  
  {% if area.location_set.all.count > 0 %}
  <p>This will also delete the following locations and their attached encounters:</p>
  <ul>
  {% for location in area.location_set.all %}
    <li>{{ location.name }} ({{ location.location_type }})</li>
      <ul>
      {% for encounter in location.encounter_set.all %}
        <li>{{ encounter.title }}</li>
      {% endfor %}
      </ul>
  {% endfor %}
  </ul>
  {% endif %}
  
  {% if area.quest_set.all.count > 0 %}
  <p>This will also delete the following quests, and their attached encounters:</p>
  
  <ol>
  {% for quest in area.quest_set.all %}
    <li>{{ quest.title }} ({{ quest.get_quest_type_display }})</li>
    <ul>
    {% for encounter in quest.encounter_set.all%}
      <li>{{ encounter.title }}</li>
    {% endfor %}
    </ul>
  {% endfor %}
  </ol>
  {% endif %}
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>

{% endblock content %}

World/templates/World/location_detail.html
{% extends 'base_generic.html' %}

{% block title %}
  <title>{{ location.name }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ location.name }}</h1>
    <a title="Edit" href="{% url 'location-update' in_project=location.in_project.id name=location.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'location-delete' in_project=location.in_project.id name=location.name %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->

  <hr class="page-title-hr">

  <div class="row">
    <div class="col-2">
    </div> <!-- col-2 -->
    <div class="col">
      <p class="flavor-text">{{ location.flavor_text }}</p>
    </div> <!-- col -->
    <div class="col-2">
    </div> <!-- col-2 -->
  </div> <!-- row -->

  <hr class="page-title-hr">

  <p>{{ location.description }}</p>

  <div class="table-title">
    <h2>Encounters (World)</h2>
    <a title="Add" href="{% url 'worldencounter-create' in_project=location.in_project.id in_location=location.name %}"><i class="cil-plus"></i></a>
  </div> <!-- table-title -->

  <table class="table table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Encounter Title</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
    {% for encounter in location.worldencounter_set.all %}
    <tr>
      <td>{{ encounter.encounter_num }}</td>
      <td><a href="{{ encounter.get_absolute_url }}">{{ encounter.title }}</a></td>
      <td>{{ encounter.get_encounter_type_display }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="table-title">
    <h2>Encounters (Quest)</h2>
  </div> <!-- table-title -->

  <table class="table table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Encounter Title</th>
        <th>Type</th>
        <th>Quest</th>
      </tr>
    </thead>
    <tbody>
    {% for encounter in location.questencounter_set.all %}
    <tr>
      <td>{{ encounter.encounter_num }}</td>
      <td><a href="{{ encounter.get_absolute_url }}">{{ encounter.title }}</a></td>
      <td>{{ encounter.get_encounter_type_display }}</td>
      <td><a href="{{ encounter.in_quest.get_absolute_url }}">{{ encounter.in_quest }}</a></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ location.name }}</th>
    </thead>
    <tbody>
      {% if location.landscape %}
      <td colspan="2">
        <img id="image" src="{{ location.landscape }}" class="img-fluid mx-auto d-block">
        <div id="imageModal" class="modal">
          <span class="close">&times;</span>
          <img class="modal-content" id="modalImage">
        </div>
      </td>
      {% endif %}
    </tbody>
    <tr>
      {% if location.in_cityquarter %}
        <th>City Quarter</th>
        <td><a href="{{ location.in_cityquarter.get_absolute_url }}">{{ location.in_cityquarter }}</a></td>
      {% elif location.in_area %}
        <th>Area</th>
        <td><a href="{{ location.in_area.get_absolute_url }}">{{ location.in_area }}</a></td>
      {% endif %}
    </tr>
    <tr>
      <th>Type</th>
      <td>{{ location.location_type }}</td>
    </tr>
    <tr>
      <th>Exits</th>
      <td>
        <ul>
        {% for exit in location.exit_points.all %}
          <li><a href="{{ exit.get_absolute_url }}">{{ exit.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>

    {% if location.dungeon_set.all.count > 0 %}
    <tr>
      <th>Dungeon</th>
      <td>
        <ul>
        {% for dungeon in location.dungeon_set.all %}
          <li><a href="{{ dungeon.get_absolute_url }}">{{ dungeon.title }}</a></li>
        {% endfor %}
      </td>
    </tr>
    {% endif %}

    <tr>
      <th>NPCs</th>
      <td>
        <ul>
        {% for npc in location.NPCs.all %}
          <li><a href="{{ npc.get_absolute_url }}">{{ npc.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Loot
        <a title="Add/Edit" href="{% url 'locationloot-create' in_project=location.in_project.id in_location=location.name %}">
          <i class="cil-plus table-icon"></i>
        </a>
      </th>
      <td>
        <ul>
        {% for loot in location.locationloot_set.all %}
          <li>
            <a href="{{ loot.name.get_absolute_url }}">{{ loot.name }}</a> ({{ loot.quantity }}x)
              <a href="{% url 'locationloot-delete' in_project=loot.in_project.id pk=loot.pk %}">
                <i class="cil-x table-icon"></i>
              </a>
          </li>
        {% endfor %}
        </ul>
      </td>
    </tr>
  </table>
{% endblock rightsidebar %}

{% block additionalscripts %}
  {% load static %}
  <script type="text/javascript" src="{% static 'js/imagemodals.js' %}"></script>
{% endblock additionalscripts %}

World/templates/World/region_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ region.name }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ region.name }}</h1>
    <a title="Edit" href="{% url 'region-update' in_project=region.in_project.id name=region.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'region-delete' in_project=region.in_project.id name=region.name %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->

  <hr class="page-title-hr">

  <p>{{ region.description }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
  <thead class="thead-dark">
    <th colspan="2" class="sidebar-table">{{ region.name }}</th>
  </thead>
  <tbody>
      {% if region.landscape %}
      <td colspan="2">
        <img id="image" src="{{ region.landscape }}" class="img-fluid mx-auto d-block">
        <div id="imageModal" class="modal">
          <span class="close">&times;</span>
          <img class="modal-content" id="modalImage">
        </div>
      </td>
      {% endif %}
    </tbody>
    <tr>
      <th>Universe</th>
      <td><a href="{{ region.in_universe.get_absolute_url }}">{{ region.in_universe }}</a></td>
    </tr>
    <tr>
      <th>Biome</th>
      <td>{{ region.get_biome_display }}</td>
    </tr>
    <tr>
      <th>Empire</th>
      <td>
        <ul>
        {% for empire in region.empire_set.all %}
          <li><a href="{{ empire.get_absolute_url }}">{{ empire.name }}</a></li>
        {% endfor %}
      </td>
    </tr>
  </table>

  <div class="table-title">
    <h4>Areas</h4>
    <a title="Add" href="{% url 'area-create' in_project=region.in_project.id in_region=region.name %}">
      <i class="cil-plus"></i>
    </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Area</th>
        <th>Type</th>
        <th>Locations</th>
      </tr>
    </thead>
    <tbody>
    {% for area in region.area_set.all %}
      <tr>
        <td><a href="{{ area.get_absolute_url }}">{{ area.name }}</a></td>
        <td>{{ area.area_type }}</td>
        <td>{{ area.location_set.all.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="table-title">
    <h4>Cities</h4>
    <a title="Add" href="{% url 'city-create' in_project=region.in_project.id in_region=region.name %}">
      <i class="cil-plus"></i>
    </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>City</th>
        <th>Quarters</th>
      </tr>
    </thead>
    <tbody>
    {% for city in region.city_set.all %}
      <tr>
        <td><a href="{{ city.get_absolute_url }}">{{ city.name }}</a></td>
        <td class="num">{{ city.cityquarter_set.all.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock rightsidebar %}

{% block additionalscripts %}
  {% load static %}
  <script type="text/javascript" src="{% static 'js/imagemodals.js' %}"></script>
{% endblock additionalscripts %}