Campaign/urls.py
from django.urls import path

from Campaign.views import campaign_detail, campaign_index, campaign_create, campaign_update, campaign_delete
from Campaign.views import chapter_detail, chapter_create, chapter_update, chapter_delete
from Campaign.views import quest_detail, quest_create, quest_update, quest_delete
from Campaign.views import questencounter_detail, questencounter_create, questencounter_update, questencounter_delete
from Campaign.views import questencounterloot_create, questencounterloot_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/c/<str:title>/index/', campaign_index, name="campaign-index"),
	path('<int:in_project>/c/<str:title>/', campaign_detail, name="campaign-detail"),
	path('<int:in_project>/ch/<str:title>/', chapter_detail, name="chapter-detail"),
	path('<int:in_project>/q/<str:title>/', quest_detail, name="quest-detail"),
	path('<int:in_project>/qe/<str:title>/', questencounter_detail, name="questencounter-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Campaigns
	path('<int:in_project>/c/create/new/', campaign_create, name="campaign-create"),
	path('<int:in_project>/c/<str:title>/update/', campaign_update, name="campaign-update"),
	path('<int:in_project>/c/<str:title>/delete/', campaign_delete, name="campaign-delete"),

	# Chapters
	path('<int:in_project>/c/<str:in_campaign>/ch/create/new/', chapter_create, name="chapter-create"),
	path('<int:in_project>/ch/<str:title>/update/', chapter_update, name="chapter-update"),
	path('<int:in_project>/ch/<str:title>/delete/', chapter_delete, name="chapter-delete"),

	# Quests
	path('<int:in_project>/ch/<str:in_chapter>/q/create/new/', quest_create, name="quest-create"),
	path('<int:in_project>/q/<str:title>/update/', quest_update, name="quest-update"),
	path('<int:in_project>/q/<str:title>/delete/', quest_delete, name="quest-delete"),

	# Quest Encounters
	path('<int:in_project>/q/<str:in_quest>/qe/create/new/', questencounter_create, name="questencounter-create"),
	path('<int:in_project>/qe/<str:title>/update/', questencounter_update, name="questencounter-update"),
	path('<int:in_project>/qe/<str:title>/delete/', questencounter_delete, name="questencounter-delete"),

	# Quest Encounter Loot
	path('<int:in_project>/qe/<str:in_questencounter>/qel/create/new/', questencounterloot_create, name="questencounterloot-create"),
	path('<int:in_project>/qel/<int:pk>/delete/', questencounterloot_delete, name="questencounterloot-delete"),
]

SovereignWorldbuilding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('homepage/', include('SovereignWebsite.urls')),
    url('worldbuilder/p/', include('Project.urls')),
    url('worldbuilder/p/', include('ItemList.urls')),
    url('worldbuilder/p/', include('Pantheon.urls')),
    url('worldbuilder/p/', include('Dungeon.urls')),
    url('worldbuilder/p/', include('Campaign.urls')),
    url('worldbuilder/p/', include('World.urls')),
    url('thelodge/', include('theLodge.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

World/urls.py
from django.urls import path

from World.views import universe_detail, universe_index, universe_create, universe_update, universe_delete
from World.views import region_detail, region_create, region_update, region_delete
from World.views import area_detail, area_create, area_update, area_delete
from World.views import city_detail, city_create, city_update, city_delete
from World.views import cityquarter_detail, cityquarter_create, cityquarter_update, cityquarter_delete
from World.views import citydemographics_create, citydemographics_delete
from World.views import location_detail, location_create, location_update, location_delete
from World.views import locationloot_create, locationloot_delete
from World.views import worldencounter_detail, worldencounter_create, worldencounter_update, worldencounter_delete
from World.views import worldencounterloot_create, worldencounterloot_delete

from World.views import empire_detail, empire_create, empire_update, empire_delete
from World.views import faction_detail, faction_create, faction_update, faction_delete
from World.views import npc_detail, npc_create, npc_update, npc_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/u/<str:name>/', universe_detail, name="universe-detail"),
	path('<int:in_project>/u/<str:name>/index/', universe_index, name="universe-index"),
	path('<int:in_project>/r/<str:name>/', region_detail, name="region-detail"),
	path('<int:in_project>/a/<str:name>/', area_detail, name="area-detail"),
	path('<int:in_project>/ct/<str:name>/', city_detail, name="city-detail"),
	path('<int:in_project>/cq/<str:name>/', cityquarter_detail, name="cityquarter-detail"),
	path('<int:in_project>/l/<str:name>/', location_detail, name="location-detail"),
	path('<int:in_project>/we/<str:title>/', worldencounter_detail, name="worldencounter-detail"),
	path('<int:in_project>/e/<str:name>/', empire_detail, name="empire-detail"),
	path('<int:in_project>/f/<str:name>/', faction_detail, name="faction-detail"),
	path('<int:in_project>/n/<str:name>/', npc_detail, name="npc-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Universes
	path('<int:in_project>/u/create/new/', universe_create, name="universe-create"),
	path('<int:in_project>/u/<str:name>/update/', universe_update, name="universe-update"),
	path('<int:in_project>/u/<str:name>/delete/', universe_delete, name="universe-delete"),

	# Regions
	path('<int:in_project>/u/<str:in_universe>/r/create/new/', region_create, name="region-create"),
	path('<int:in_project>/r/<str:name>/update/', region_update, name="region-update"),
	path('<int:in_project>/r/<str:name>/delete/', region_delete, name="region-delete"),

	# Areas
	path('<int:in_project>/r/<str:in_region>/a/create/new/', area_create, name="area-create"),
	path('<int:in_project>/a/<str:name>/update/', area_update, name="area-update"),
	path('<int:in_project>/a/<str:name>/delete/', area_delete, name="area-delete"),

	# Cities
	path('<int:in_project>/r/<str:in_region>/ct/create/new/', city_create, name="city-create"),
	path('<int:in_project>/ct/<str:name>/update/', city_update, name="city-update"),
	path('<int:in_project>/ct/<str:name>/delete/', city_delete, name="city-delete"),

	# City Quarters
	path('<int:in_project>/c/<str:in_city>/cq/create/new/', cityquarter_create, name="cityquarter-create"),
	path('<int:in_project>/cq/<str:name>/update/', cityquarter_update, name="cityquarter-update"),
	path('<int:in_project>/cq/<str:name>/delete/', cityquarter_delete, name="cityquarter-delete"),

	# City Demographics
	path('<int:in_project>/ct/<str:in_city>/ctd/create/new/', citydemographics_create, name="citydemographics-create"),
	path('<int:in_project>/ctd/<int:pk>/delete/', citydemographics_delete, name="citydemographics-delete"),

	# Locations
	path('<int:in_project>/a/<str:in_area>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/cq/<str:in_cityquarter>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/l/<str:name>/delete/', location_delete, name="location-delete"),

	# Location Loot
	path('<int:in_project>/l/<str:in_location>/ll/create/new/', locationloot_create, name="locationloot-create"),
	path('<int:in_project>/ll/<int:pk>/delete/', locationloot_delete, name="locationloot-delete"),

	# World Encounter
	path('<int:in_project>/rm/<str:in_dungeon_room>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/l/<str:in_location>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/we/<str:title>/update/', worldencounter_update, name="worldencounter-update"),
	path('<int:in_project>/we/<str:title>/delete/', worldencounter_delete, name="worldencounter-delete"),

	# World Encounter Loot
	path('<int:in_project>/we/<str:in_worldencounter>/wel/create/new/', worldencounterloot_create, name="worldencounterloot-create"),
	path('<int:in_project>/wel/<int:pk>/delete/', worldencounterloot_delete, name="worldencounterloot-delete"),

	# Empires
	path('<int:in_project>/u/<str:in_universe>/e/create/new/', empire_create, name="empire-create"),
	path('<int:in_project>/e/<str:name>/update/', empire_update, name="empire-update"),
	path('<int:in_project>/e/<str:name>/delete/', empire_delete, name="empire-delete"),

	# Factions
	path('<int:in_project>/u/<str:in_universe>/f/create/new/', faction_create, name="faction-create"),
	path('<int:in_project>/f/<str:name>/update/', faction_update, name="faction-update"),
	path('<int:in_project>/f/<str:name>/delete/', faction_delete, name="faction-delete"),

	# NPCs
	path('<int:in_project>/u/<str:in_universe>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/u/<str:in_universe>/f/<str:in_faction>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/f/<str:in_faction>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/n/<str:name>/delete/', npc_delete, name="npc-delete"),
]

Campaign/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

from ItemList.models import Item
from World.models import Location, NPC, Region, Area, City
from Dungeon.models import Room
from World.models import Universe
from Project.models import Project

class Campaign(models.Model):
	title = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey(Universe, on_delete=models.SET_NULL, blank=True, null=True)

	overview = models.TextField(blank=True, null=True)

	def get_absolute_url(self):
		return reverse('campaign-detail', args=[str(self.in_project.id), str(self.title)])

	def get_absolute_index_url(self):
		return reverse('campaign-index', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class Chapter(models.Model):
	title = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
	chapter_num = models.IntegerField()

	summary = models.TextField(blank=True, null=True)

	involved_npcs = models.ManyToManyField(NPC, blank=True, related_name="involvednpcs")

	regions = models.ManyToManyField(Region, blank=True)

	class Meta:
		ordering = ['chapter_num', ]

	def get_absolute_url(self):
		return reverse('chapter-detail', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class Quest(models.Model):
	title = models.CharField(max_length=255)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)

	QUEST_TYPES = (
		('mq', 'Main Quest'),
		('sq', 'Side Quest'),
	)

	quest_type = models.CharField(max_length=2, choices=QUEST_TYPES)
	quest_num = models.IntegerField()

	in_chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
	in_areas = models.ManyToManyField(Area, blank=True)
	in_cities = models.ManyToManyField(City, blank=True)

	summary = models.TextField(blank=True, null=True)

	involved_npcs = models.ManyToManyField(NPC, blank=True)

	class Meta:
		ordering = ['quest_num', ]

	def get_absolute_url(self):
		return reverse('quest-detail', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class QuestEncounter(models.Model):
	title = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_quest = models.ForeignKey(Quest, on_delete=models.CASCADE)
	encounter_num = models.IntegerField(blank=True, null=True)
	in_location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
	in_dungeon_room = models.ForeignKey(Room, on_delete=models.SET_NULL, blank=True, null=True)

	ENCOUNTER_TYPES = (
		('gbe', 'Grid-based'),
		('totme', 'Theater-of-the-Mind'),
		('lbe', 'Lore-based'),
	)
	encounter_type = models.CharField(max_length=5, choices=ENCOUNTER_TYPES, blank=True, null=True)

	dramatic_question = models.CharField(max_length=255, blank=True, null=True)
	summary = models.TextField(blank=True, null=True)
	flavor_text = models.TextField(max_length=2500, blank=True, null=True)

	involved_npcs = models.ManyToManyField(NPC, blank=True)

	class Meta:
		ordering = ['encounter_num']

	def get_absolute_url(self):
		return reverse('questencounter-detail', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class QuestEncounterLoot(models.Model):
	name = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_questencounter = models.ForeignKey(QuestEncounter, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "Quest Encounter Loot"
		order_with_respect_to = 'name'

	def __str__(self):
		return self.name.name

Campaign/templates/Campaign/campaign_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ campaign }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Campaign/templates/Campaign/campaign_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ campaign.title }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <a title="Index" class="storage-icon" href="{{ campaign.get_absolute_index_url }}">
      <i class="cil-storage"></i>
    </a>
    <h1>{{ campaign.title }}</h1>
    <a title="Edit" href="{% url 'campaign-update' in_project=campaign.in_project.id title=campaign.title %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'campaign-delete' in_project=campaign.in_project.id title=campaign.title %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->
  <hr class="page-title-hr">

  <p>{{ campaign.overview }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ campaign.title }}</th>
    </thead>
    <tr>
      <th>Project</th>
      <td><a href="{{ campaign.in_project.get_absolute_url }}">{{ campaign.in_project.title }}</a></td>
    </tr>
    <tr>
      <th>Universe</th>
      <td><a href="{{ campaign.in_universe.get_absolute_url }}">{{ campaign.in_universe }}</a></td>
    </tr>
  </table>

  <div class="table-title">
      <h4>Chapters</h4>
      <a title="Add" href="{% url 'chapter-create' in_project=campaign.in_project.id in_campaign=campaign.title %}">
        <i class="cil-plus"></i>
      </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Chapter Title</th>
        <th>Regions</th>
      </tr>
    </thead>
    <tbody>
    {% for chapter in chapters %}
      <tr>
        <td class="num">{{ chapter.chapter_num }}</td>
        <td><a href="{{ chapter.get_absolute_url}}">{{ chapter.title }}</a></td>
        <td>
          {% for region in chapter.regions.all %}
            <a href="{{ region.get_absolute_url }}">{{ region.name }}</a> |
          {% endfor %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

Campaign/templates/Campaign/chapter_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ chapter }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Campaign/templates/Campaign/chapter_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ chapter.title }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ chapter.title }}</h1>
    <a title="Edit" href="{% url 'chapter-update' in_project=chapter.in_project.id title=chapter.title %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'chapter-delete' in_project=chapter.in_project.id title=chapter.title %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->
  <hr class="page-title-hr">

  <p>{{ chapter.summary }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ chapter.title }}</th>
    </thead>
    <tr>
      <th>Campaign</th>
      <td><a href="{{ chapter.in_campaign.get_absolute_url }}">{{ chapter.in_campaign }}</a></td>
    </tr>
    <tr>
      <th>Preceded By</th>
      <td>
        <ul>
        {% for previous in preceded_by %}
          <li><a href="{{ previous.get_absolute_url }}">{{ previous.title }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>

    <tr>
      <th>Followed By</th>
      <td>
        <ul>
        {% for next in followed_by %}
          <li><a href="{{ next.get_absolute_url }}">{{ next.title }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Regions</th>
      <td>
        <ul>
        {% for region in chapter.regions.all %}
          <li><a href="{{ region.get_absolute_url }}">{{ region.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>

    <tr>
      <th>NPCs</th>
      <td>
        <ul>
        {% for npc in chapter.involved_npcs.all %}
          <li><a href="{{ npc.get_absolute_url }}">{{ npc.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
  </table>

  <div class="table-title">
      <h4>Main Quests</h4>
      <a title="Add" href="{% url 'quest-create' in_project=chapter.in_project.id in_chapter=chapter.title %}">
        <i class="cil-plus"></i>
      </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Encounters</th>
      </tr>
    </thead>
    <tbody>
    {% for quest in main_quests %}
      <tr>
        <td>{{ quest.quest_num }}</td>
        <td><a href="{{ quest.get_absolute_url }}">{{ quest.title}}</a></td>
        <td>{{ quest.questencounter_set.all.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="table-title">
      <h4>Side Quests</h4>
      <a title="Add" href="{% url 'quest-create' in_project=chapter.in_project.id in_chapter=chapter.title %}">
        <i class="cil-plus"></i>
      </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Encounters</th>
      </tr>
    </thead>
    <tbody>
    {% for quest in side_quests %}
      <tr>
        <td>{{ quest.quest_num }}</td>
        <td><a href="{{ quest.get_absolute_url }}">{{ quest.title}}</a></td>
        <td>{{ quest.questencounter_set.all.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

Campaign/templates/Campaign/quest_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ quest.title }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ quest.title }}</h1>
    <a title="Edit" href="{% url 'quest-update' in_project=quest.in_project.id title=quest.title %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'quest-delete' in_project=quest.in_project.id title=quest.title %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->
  <hr class="page-title-hr">

  <p>{{ quest.summary }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ quest.title }}</th>
    </thead>
    <tr>
      <th>Chapter</th>
      <td>
        <a href="{{ quest.in_chapter.get_absolute_url }}">{{ quest.in_chapter }}</a>
      </td>
    </tr>
    <tr>
      <th>Type</th>
      <td>{{ quest.get_quest_type_display }}
    </tr>

    <tr>
      <th>Areas & Cities</th>
      <td>
        <ul>
        {% for area in quest.in_areas.all %}
          <li><a href="{{ area.get_absolute_url }}">{{ area.name }}</a></li>
        {% endfor %}
        {% for city in quest.in_cities.all %}
          <li><a href="{{ city.get_absolute_url }}">{{ city.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>

    <tr>
      <th>Preceded By</th>
      <td>
        <ul>
        {% for previous in preceded_by %}
          <li><a href="{{ previous.get_absolute_url }}">{{ previous.title }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Followed By</th>
      <td>
        <ul>
        {% for next in followed_by %}
          <li><a href="{{ next.get_absolute_url }}">{{ next.title }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>NPCs</th>
      <td>
        <ul>
        {% for npc in quest.involved_npcs.all %}
          <li><a href="{{ npc.get_absolute_url }}">{{ npc.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
  </table>

  <div class="table-title">
    <h4>Encounters</h4>
    <a title="Add" href="{% url 'questencounter-create' in_project=quest.in_project.id in_quest=quest.title %}">
      <i class="cil-plus"></i>
    </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Encounter Title</th>
        <th>Type</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
    {% for encounter in quest.questencounter_set.all %}
    <tr>
      <td>{{ encounter.encounter_num }}</td>
      <td><a href="{{ encounter.get_absolute_url }}">{{ encounter.title }}</td>
      <td>{{ encounter.get_encounter_type_display }}</td>
      {% if encounter.in_location %}
        <td>
          <a href="{{ encounter.in_location.get_absolute_url }}">{{ encounter.in_location }}
          </a>
        </td>
      {% elif encounter.in_dungeon_room %}
        <td>
          <a href="{{ encounter.in_dungeon_room.get_absolute_url}}">{{ encounter.in_dungeon_room }}</a>
        </td>
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

Campaign/templates/Campaign/questencounter_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ questencounter.title }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ questencounter.encounter_num }}. {{ questencounter.title }}</h1>
    <a title="Edit" href="{% url 'questencounter-update' in_project=questencounter.in_project.id title=questencounter.title %}"><i class="cil-pencil"></i></a>
    <a title="Delete" href="{% url 'questencounter-delete' in_project=questencounter.in_project.id title=questencounter.title %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->

  <hr class="page-title-hr">

  <div class="row">
    <div class="col-2">
    </div> <!-- col-2 -->
    <div class="col">
      <p class="flavor-text">{{ questencounter.flavor_text }}</p>
    </div> <!-- col -->
    <div class="col-2">
    </div> <!-- col-2 -->
  </div> <!-- row -->

  <hr class="page-title-hr">

  <p class="dramatic-question">{{ questencounter.dramatic_question }}</p>

  <p>{{ questencounter.summary }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ questencounter.title }}</th>
    </thead>
    <tr>
      <th>Quest</th>
      <td>
        <a href="{{ questencounter.in_quest.get_absolute_url }}">{{ questencounter.in_quest }}</a>
      </td>
    </tr>
    <tr>
    {% if questencounter.in_dungeon_room %}
      <th>Dungeon Room</th>
      <td><a href="{{ questencounter.in_dungeon_room.get_absolute_url }}">{{ questencounter.in_dungeon_room }}</a></td>
    {% elif questencounter.in_location %}
      <th>Location</th>
      <td>
        <a href="{{ questencounter.in_location.get_absolute_url }}">{{ questencounter.in_location }}</a>
      </td>
    {% endif %}
    </tr>
    <tr>
      <th>Type</th>
      <td>{{ questencounter.get_encounter_type_display }}</td>
    </tr>
    <tr>
      <th>NPCs</th>
      <td>
        <ul>
        {% for npc in questencounter.involved_npcs.all %}
          <li><a href="{{ npc.get_absolute_url }}">{{ npc.name}}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Loot
        <a title="Add" href="{% url 'questencounterloot-create' in_project=questencounter.in_project.id in_questencounter=questencounter.title %}">
          <i class="cil-plus table-icon"></i>
        </a>
      </th>
      <td>
        <ul>
        {% for loot in questencounter.questencounterloot_set.all %}
          <li><a href="{{ loot.name.get_absolute_url }}">{{ loot.name }}</a> ({{ loot.quantity }}x)
            <a href="{% url 'questencounterloot-delete' in_project=loot.in_project.id pk=loot.pk %}">
              <i class="cil-x table-icon"></i>
            </a>
          </li>
        {% endfor %}
        </ul>
      </td>
    </tr>
  </table>
{% endblock rightsidebar %}