Pantheon/urls.py
from django.urls import path

from Pantheon.views import pantheon_detail, pantheon_create, pantheon_update, pantheon_delete
from Pantheon.views import god_detail, god_create, god_update, god_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/pa/<str:name>/', pantheon_detail, name="pantheon-detail"),
	path('<int:in_project>/g/<str:name>/', god_detail, name="god-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Pantheons
	path('<int:in_project>/u/<str:in_universe>/pa/create/new/', pantheon_create, name="pantheon-create"),
	path('<int:in_project>/pa/<str:name>/update/', pantheon_update, name="pantheon-update"),
	path('<int:in_project>/pa/<str:name>/delete/', pantheon_delete, name="pantheon-delete"),

	# Gods
	path('<int:in_project>/pa/<str:in_pantheon>/g/create/new/', god_create, name="god-create"),
	path('<int:in_project>/g/<str:name>/update/', god_update, name="god-update"),
	path('<int:in_project>/g/<str:name>/delete/', god_delete, name="god-delete"),
]

SovereignWorldbuilding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('homepage/', include('SovereignWebsite.urls')),
    url('worldbuilder/p/', include('Project.urls')),
    url('worldbuilder/p/', include('ItemList.urls')),
    url('worldbuilder/p/', include('Pantheon.urls')),
    url('worldbuilder/p/', include('Dungeon.urls')),
    url('worldbuilder/p/', include('Campaign.urls')),
    url('worldbuilder/p/', include('World.urls')),
    url('thelodge/', include('theLodge.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

World/urls.py
from django.urls import path

from World.views import universe_detail, universe_index, universe_create, universe_update, universe_delete
from World.views import region_detail, region_create, region_update, region_delete
from World.views import area_detail, area_create, area_update, area_delete
from World.views import city_detail, city_create, city_update, city_delete
from World.views import cityquarter_detail, cityquarter_create, cityquarter_update, cityquarter_delete
from World.views import citydemographics_create, citydemographics_delete
from World.views import location_detail, location_create, location_update, location_delete
from World.views import locationloot_create, locationloot_delete
from World.views import worldencounter_detail, worldencounter_create, worldencounter_update, worldencounter_delete
from World.views import worldencounterloot_create, worldencounterloot_delete

from World.views import empire_detail, empire_create, empire_update, empire_delete
from World.views import faction_detail, faction_create, faction_update, faction_delete
from World.views import npc_detail, npc_create, npc_update, npc_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/u/<str:name>/', universe_detail, name="universe-detail"),
	path('<int:in_project>/u/<str:name>/index/', universe_index, name="universe-index"),
	path('<int:in_project>/r/<str:name>/', region_detail, name="region-detail"),
	path('<int:in_project>/a/<str:name>/', area_detail, name="area-detail"),
	path('<int:in_project>/ct/<str:name>/', city_detail, name="city-detail"),
	path('<int:in_project>/cq/<str:name>/', cityquarter_detail, name="cityquarter-detail"),
	path('<int:in_project>/l/<str:name>/', location_detail, name="location-detail"),
	path('<int:in_project>/we/<str:title>/', worldencounter_detail, name="worldencounter-detail"),
	path('<int:in_project>/e/<str:name>/', empire_detail, name="empire-detail"),
	path('<int:in_project>/f/<str:name>/', faction_detail, name="faction-detail"),
	path('<int:in_project>/n/<str:name>/', npc_detail, name="npc-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Universes
	path('<int:in_project>/u/create/new/', universe_create, name="universe-create"),
	path('<int:in_project>/u/<str:name>/update/', universe_update, name="universe-update"),
	path('<int:in_project>/u/<str:name>/delete/', universe_delete, name="universe-delete"),

	# Regions
	path('<int:in_project>/u/<str:in_universe>/r/create/new/', region_create, name="region-create"),
	path('<int:in_project>/r/<str:name>/update/', region_update, name="region-update"),
	path('<int:in_project>/r/<str:name>/delete/', region_delete, name="region-delete"),

	# Areas
	path('<int:in_project>/r/<str:in_region>/a/create/new/', area_create, name="area-create"),
	path('<int:in_project>/a/<str:name>/update/', area_update, name="area-update"),
	path('<int:in_project>/a/<str:name>/delete/', area_delete, name="area-delete"),

	# Cities
	path('<int:in_project>/r/<str:in_region>/ct/create/new/', city_create, name="city-create"),
	path('<int:in_project>/ct/<str:name>/update/', city_update, name="city-update"),
	path('<int:in_project>/ct/<str:name>/delete/', city_delete, name="city-delete"),

	# City Quarters
	path('<int:in_project>/c/<str:in_city>/cq/create/new/', cityquarter_create, name="cityquarter-create"),
	path('<int:in_project>/cq/<str:name>/update/', cityquarter_update, name="cityquarter-update"),
	path('<int:in_project>/cq/<str:name>/delete/', cityquarter_delete, name="cityquarter-delete"),

	# City Demographics
	path('<int:in_project>/ct/<str:in_city>/ctd/create/new/', citydemographics_create, name="citydemographics-create"),
	path('<int:in_project>/ctd/<int:pk>/delete/', citydemographics_delete, name="citydemographics-delete"),

	# Locations
	path('<int:in_project>/a/<str:in_area>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/cq/<str:in_cityquarter>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/l/<str:name>/delete/', location_delete, name="location-delete"),

	# Location Loot
	path('<int:in_project>/l/<str:in_location>/ll/create/new/', locationloot_create, name="locationloot-create"),
	path('<int:in_project>/ll/<int:pk>/delete/', locationloot_delete, name="locationloot-delete"),

	# World Encounter
	path('<int:in_project>/rm/<str:in_dungeon_room>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/l/<str:in_location>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/we/<str:title>/update/', worldencounter_update, name="worldencounter-update"),
	path('<int:in_project>/we/<str:title>/delete/', worldencounter_delete, name="worldencounter-delete"),

	# World Encounter Loot
	path('<int:in_project>/we/<str:in_worldencounter>/wel/create/new/', worldencounterloot_create, name="worldencounterloot-create"),
	path('<int:in_project>/wel/<int:pk>/delete/', worldencounterloot_delete, name="worldencounterloot-delete"),

	# Empires
	path('<int:in_project>/u/<str:in_universe>/e/create/new/', empire_create, name="empire-create"),
	path('<int:in_project>/e/<str:name>/update/', empire_update, name="empire-update"),
	path('<int:in_project>/e/<str:name>/delete/', empire_delete, name="empire-delete"),

	# Factions
	path('<int:in_project>/u/<str:in_universe>/f/create/new/', faction_create, name="faction-create"),
	path('<int:in_project>/f/<str:name>/update/', faction_update, name="faction-update"),
	path('<int:in_project>/f/<str:name>/delete/', faction_delete, name="faction-delete"),

	# NPCs
	path('<int:in_project>/u/<str:in_universe>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/u/<str:in_universe>/f/<str:in_faction>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/f/<str:in_faction>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/n/<str:name>/delete/', npc_delete, name="npc-delete"),
]

Pantheon/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

from Project.models import Project

class Pantheon(models.Model):
	name = models.CharField(max_length=125)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_universe = models.ForeignKey('World.Universe', on_delete=models.CASCADE)

	background = models.TextField(blank=True, null=True)

	def get_absolute_url(self):
		return reverse('pantheon-detail', args=[str(self.in_project.id), str(self.name)])

	class Meta:
		ordering = ['name', ]

	def __str__(self):
		return self.name

class God(models.Model):
	name = models.CharField(max_length=125)
	alternative_names = models.CharField(max_length=255, blank=True, null=True)

	ALIGNMENTS = (
		('LG', 'Lawful/Good'),
		('NG', 'Neutral/Good'),
		('CG', 'Chaotic/Good'),
		('LN', 'Lawful/Neutral'),
		('N', 'True Neutral'),
		('CN', 'Chaotic/Neutral'),
		('LE', 'Lawful/Evil'),
		('NE', 'Neutral/Evil'),
		('CE', 'Chaotic/Evil'),
	)

	alignment = models.CharField(max_length=2, choices=ALIGNMENTS, blank=True, null=True)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_pantheon = models.ForeignKey(Pantheon, on_delete=models.CASCADE)

	background = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['name', ]

	def get_absolute_url(self):
		return reverse('god-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

Pantheon/forms.py
from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

from Pantheon.models import Pantheon, God

class PantheonModelForm(ModelForm):
	class Meta:
		model = Pantheon
		fields = '__all__'

	def clean_name(self):
		data = self.cleaned_data['name']
		if '/' in data:
			msg = "'/' is not a valid character."
			raise forms.ValidationError(msg)
		if not self.instance.name == data:
			if self.pantheons.filter(name=data).exists():
				msg = "%s is already in this project" % data
				raise forms.ValidationError(msg)
		return data

	def __init__(self, pantheons, *args, **kwargs):
		super(PantheonModelForm, self).__init__(*args, **kwargs)
		self.pantheons = pantheons

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Field('name'),
			Field('background', id="textarea"),
			Field('in_project', type="hidden"),
			Field('in_universe', type="hidden"),
		)

class GodModelForm(ModelForm):
	class Meta:
		model = God
		fields = '__all__'

	def clean_name(self):
		data = self.cleaned_data['name']
		if '/' in data:
			msg = "'/' is not a valid character."
			raise forms.ValidationError(msg)
		if not self.instance.name == data:
			if self.gods.filter(name=data).exists():
				msg = "%s already exists in this project." % data
				raise forms.ValidationError(msg)
		return data

	def __init__(self, gods, *args, **kwargs):
		super(GodModelForm, self).__init__(*args, **kwargs)
		self.gods = gods

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Field('name'),
			Field('alternative_names'),
			Field('alignment'),
			Field('background', id="textarea"),
			Field('in_project', type="hidden"),
			Field('in_pantheon', type="hidden"),
		)

Pantheon/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse

from Pantheon.forms import PantheonModelForm, GodModelForm

from Pantheon.models import Pantheon, God
from World.models import Universe, Faction, NPC
from Project.models import Project

from Pantheon import decorators

##################
###   #VIEWS   ###
##################

@login_required
@decorators.pantheon_in_user_library
def pantheon_detail(request, in_project, name):
	project = Project.objects.get(id=in_project)
	pantheons = project.pantheon_set.all()
	pantheon = get_object_or_404(pantheons, name=name)

	context = {'pantheon': pantheon}

	return render(request, "pantheon_detail.html", context)

@login_required
@decorators.god_in_user_library
def god_detail(request, in_project, name):
	project = Project.objects.get(id=in_project)
	gods = project.god_set.all()
	god = get_object_or_404(gods, name=name)
	worshipped_by_npcs = project.npc_set.filter(faiths=god)
	worshipped_by_factions = project.faction_set.filter(faiths=god)

	context = {
		'god': god,
		'worshipped_by_npcs': worshipped_by_npcs,
		'worshipped_by_factions': worshipped_by_factions,
	}

	return render(request, "god_detail.html", context)


################
###   #FORMS ###
################

@login_required
@decorators.create_pantheon_in_user_library
def pantheon_create(request, in_project, in_universe):
	in_project = Project.objects.get(id=in_project)
	in_universe = in_project.universe_set.get(name=in_universe)
	pantheons = in_project.pantheon_set.all()

	pantheon = Pantheon()

	form = PantheonModelForm(pantheons,
							 request.POST or None,
							 initial={'in_project': in_project, 'in_universe': in_universe},
							 instance=pantheon
							)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(
					reverse('pantheon-detail',
						args=[
							str(pantheon.in_project.id),
							str(pantheon.name)
					]))

	return render(request, 'pantheon_form.html', {'form': form})

@login_required
@decorators.pantheon_in_user_library
def pantheon_update(request, in_project, name):
	in_project = Project.objects.get(id=in_project)
	pantheons = in_project.pantheon_set.all()
	pantheon = get_object_or_404(pantheons, name=name)

	in_universe = pantheon.in_universe


	form = PantheonModelForm(pantheons,
							 request.POST or None,
							 initial={'in_project': in_project, 'in_universe': in_universe},
							 instance=pantheon
							)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(
					reverse('pantheon-detail',
						args=[
							str(pantheon.in_project.id),
							str(pantheon.name)
					]))

	return render(request, 'pantheon_form.html', {'form': form})

@login_required
@decorators.pantheon_in_user_library
def pantheon_delete(request, in_project, name):
	try:
		pantheon = Pantheon.objects.filter(in_project=in_project).get(name=name)
	except ObjectDoesNotExist:
		raise Http404

	if request.method == 'POST':
		pantheon.delete()
		return HttpResponseRedirect(
				reverse('universe-detail',
					args=[
						str(pantheon.in_project.id),
						str(pantheon.in_universe.name)])
				)

	return render(request, "pantheon_confirm_delete.html", context={'pantheon': pantheon})

@login_required
@decorators.create_god_in_user_library
def god_create(request, in_project, in_pantheon):
	in_project = Project.objects.get(id=in_project)
	in_pantheon = in_project.pantheon_set.get(name=in_pantheon)
	gods = in_project.god_set.all()

	god = God()

	form = GodModelForm(gods,
						request.POST or None,
						initial={'in_project': in_project, 'in_pantheon': in_pantheon},
						instance=god
					)

	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(
					reverse('god-detail',
						args=[
							str(god.in_project.id),
							str(god.name)
					]))

	return render(request, 'god_form.html', {'form': form})

@login_required
@decorators.god_in_user_library
def god_update(request, in_project, name):
	in_project = Project.objects.get(id=in_project)
	gods = in_project.god_set.all()

	god = get_object_or_404(gods, name=name)

	in_pantheon = god.in_pantheon

	form = GodModelForm(gods,
						request.POST or None,
						initial={'in_project': in_project, 'in_pantheon': in_pantheon},
						instance=god
					)

	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(
					reverse('god-detail',
						args=[
							str(god.in_project.id),
							str(god.name)
					]))

	return render(request, 'god_form.html', {'form': form})

@login_required
@decorators.god_in_user_library
def god_delete(request, in_project, name):
	in_project = Project.objects.get(id=in_project)
	gods = in_project.god_set.all()

	god = get_object_or_404(gods, name=name)

	if request.method == 'POST':
		god.delete()
		return HttpResponseRedirect(
				reverse('pantheon-detail',
					args=[
						str(god.in_project.id),
						str(god.in_pantheon.name)])
					)
	return render(request, "god_confirm_delete.html", context={'god': god})

Pantheon/templates/Pantheon/god_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ god }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Pantheon/templates/Pantheon/god_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ god.name }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ god.name }}</h1>
    <a title="Edit" href="{% url 'god-update' in_project=god.in_project.id name=god.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'god-delete' in_project=god.in_project.id name=god.name %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->

  <hr class="page-title-hr">

  <p>{{ god.background }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ god.name }}</th>
    </thead>
    <tr>
      <th>Pantheon</th>
      <td><a href="{{ god.in_pantheon.get_absolute_url }}">{{ god.in_pantheon }}</a></td>
    </tr>
    <tr>
      <th>Alignment</th>
      <td>{{ god.get_alignment_display }}</td>
    </tr>
    <tr>
      <th>Alternative Names</th>
      <td>{{ god.alternative_names }}</td>
    </tr>
    <tr>
      <th>Worshipped by (NPCs)</th>
      <td>
        <ul>
        {% for npc in worshipped_by_npcs %}
          <li><a href="{{ npc.get_absolute_url }}">{{ npc.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Worshipped by (Factions)</th>
      <td>
        <ul>
        {% for faction in worshipped_by_factions %}
          <li><a href="{{ faction.get_absolute_url }}">{{ faction.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
  </table>
{% endblock rightsidebar %}

Pantheon/templates/Pantheon/god_form.html
{% extends "base_generic.html" %}

{% block additionalstatic %}
  <script src="https://cdn.tiny.cloud/1/2gcz381i62l40q1b09f9459xib3itxlfnxcb70ye30po1t96/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  {% load static %}
  <script src="{% static 'js/tinymce_config.js' %}"></script>
{% endblock additionalstatic %}

{% block content %}

  <h1 class="page-title">Add/Edit God</h1>
  <hr class="page-title-hr">
  
  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}

Pantheon/templates/Pantheon/pantheon_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ pantheon }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Pantheon/templates/Pantheon/pantheon_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ pantheon.name }}</title>
{% endblock title %}}

{% block content %}
  <div class="page-title">
    <h1>{{ pantheon.name }}</h1>
    <a title="Edit" href="{% url 'pantheon-update' in_project=pantheon.in_project.id name=pantheon.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'pantheon-delete' in_project=pantheon.in_project.id name=pantheon.name %}">
      <i class="cil-x"></i>
    </a>
  </div> <!-- page-title and icons -->

  <hr class="page-title-hr">

  <p>{{ pantheon.background }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <th colspan="2" class="sidebar-table">{{ pantheon.name }}</th>
    </thead>
    <tr>
      <th>Universe</th>
      <td><a href="{{ pantheon.in_universe.get_absolute_url }}">{{ pantheon.in_universe }}</a></td>
    </tr>
  </table>

  <div class="table-title">
    <h4>Gods</h4>
    <a title="Add" href="{% url 'god-create' in_project=pantheon.in_project.id in_pantheon=pantheon.name %}">
      <i class="cil-plus"></i>
    </a>
  </div>

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>God</th>
        <th>Alignment</th>
      </tr>
    </thead>
    <tbody>
    {% for god in pantheon.god_set.all %}
      <tr>
        <td><a href="{{ god.get_absolute_url }}">{{ god.name }}</a></td>
        <td>{{ god.get_alignment_display }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

Pantheon/templates/Pantheon/pantheon_form.html
{% extends 'base_generic.html' %}

{% block additionalstatic %}
  <script src="https://cdn.tiny.cloud/1/2gcz381i62l40q1b09f9459xib3itxlfnxcb70ye30po1t96/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  {% load static %}
  <script src="{% static 'js/tinymce_config.js' %}"></script>
{% endblock additionalstatic %}

{% block content %}

  <h1 class="page-title">Add/Edit Pantheon</h1>
  <hr class="page-title-hr">

  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}