Dungeon/urls.py
from django.urls import path

from Dungeon.views import dungeon_detail, dungeon_create, dungeon_update, dungeon_delete
from Dungeon.views import roomset_detail, roomset_create, roomset_update, roomset_delete
from Dungeon.views import room_detail, room_create, room_update, room_delete
from Dungeon.views import roomloot_create, roomloot_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/d/<str:title>/', dungeon_detail, name="dungeon-detail"),
	path('<int:in_project>/rs/<str:name>/', roomset_detail, name="roomset-detail"),
	path('<int:in_project>/rm/<str:name>/', room_detail, name="room-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Dungeons
	path('<int:in_project>/a/<str:in_area>/d/create/new/', dungeon_create, name="dungeon-create"),
	path('<int:in_project>/d/<str:title>/update/', dungeon_update, name="dungeon-update"),
	path('<int:in_project>/d/<str:title>/delete/', dungeon_delete, name="dungeon-delete"),

	# Roomsets
	path('<int:in_project>/d/<str:in_dungeon>/rs/create/new/', roomset_create, name="roomset-create"),
	path('<int:in_project>/rs/<str:name>/update/', roomset_update, name="roomset-update"),
	path('<int:in_project>/rs/<str:name>/delete/', roomset_delete, name="roomset-delete"),

	# Rooms
	path('<int:in_project>/rs/<str:in_roomset>/rm/create/new/', room_create, name="room-create"),
	path('<int:in_project>/rm/<str:name>/update/', room_update, name="room-update"),
	path('<int:in_project>/rm/<str:name>/delete/', room_delete, name="room-delete"),

	# Room Loot
	path('<int:in_project>/rm/<str:in_room>/rl/create/new/', roomloot_create, name="roomloot-create"),
	path('<int:in_project>/rl/<int:pk>/delete/', roomloot_delete, name="roomloot-delete"),
]

SovereignWorldbuilding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('homepage/', include('SovereignWebsite.urls')),
    url('worldbuilder/p/', include('Project.urls')),
    url('worldbuilder/p/', include('ItemList.urls')),
    url('worldbuilder/p/', include('Pantheon.urls')),
    url('worldbuilder/p/', include('Dungeon.urls')),
    url('worldbuilder/p/', include('Campaign.urls')),
    url('worldbuilder/p/', include('World.urls')),
    url('thelodge/', include('theLodge.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

World/urls.py
from django.urls import path

from World.views import universe_detail, universe_index, universe_create, universe_update, universe_delete
from World.views import region_detail, region_create, region_update, region_delete
from World.views import area_detail, area_create, area_update, area_delete
from World.views import city_detail, city_create, city_update, city_delete
from World.views import cityquarter_detail, cityquarter_create, cityquarter_update, cityquarter_delete
from World.views import citydemographics_create, citydemographics_delete
from World.views import location_detail, location_create, location_update, location_delete
from World.views import locationloot_create, locationloot_delete
from World.views import worldencounter_detail, worldencounter_create, worldencounter_update, worldencounter_delete
from World.views import worldencounterloot_create, worldencounterloot_delete

from World.views import empire_detail, empire_create, empire_update, empire_delete
from World.views import faction_detail, faction_create, faction_update, faction_delete
from World.views import npc_detail, npc_create, npc_update, npc_delete

urlpatterns = []

# Detail Views
urlpatterns += [
	path('<int:in_project>/u/<str:name>/', universe_detail, name="universe-detail"),
	path('<int:in_project>/u/<str:name>/index/', universe_index, name="universe-index"),
	path('<int:in_project>/r/<str:name>/', region_detail, name="region-detail"),
	path('<int:in_project>/a/<str:name>/', area_detail, name="area-detail"),
	path('<int:in_project>/ct/<str:name>/', city_detail, name="city-detail"),
	path('<int:in_project>/cq/<str:name>/', cityquarter_detail, name="cityquarter-detail"),
	path('<int:in_project>/l/<str:name>/', location_detail, name="location-detail"),
	path('<int:in_project>/we/<str:title>/', worldencounter_detail, name="worldencounter-detail"),
	path('<int:in_project>/e/<str:name>/', empire_detail, name="empire-detail"),
	path('<int:in_project>/f/<str:name>/', faction_detail, name="faction-detail"),
	path('<int:in_project>/n/<str:name>/', npc_detail, name="npc-detail"),
]

# Create, Update and Delete Views
urlpatterns += [
	# Universes
	path('<int:in_project>/u/create/new/', universe_create, name="universe-create"),
	path('<int:in_project>/u/<str:name>/update/', universe_update, name="universe-update"),
	path('<int:in_project>/u/<str:name>/delete/', universe_delete, name="universe-delete"),

	# Regions
	path('<int:in_project>/u/<str:in_universe>/r/create/new/', region_create, name="region-create"),
	path('<int:in_project>/r/<str:name>/update/', region_update, name="region-update"),
	path('<int:in_project>/r/<str:name>/delete/', region_delete, name="region-delete"),

	# Areas
	path('<int:in_project>/r/<str:in_region>/a/create/new/', area_create, name="area-create"),
	path('<int:in_project>/a/<str:name>/update/', area_update, name="area-update"),
	path('<int:in_project>/a/<str:name>/delete/', area_delete, name="area-delete"),

	# Cities
	path('<int:in_project>/r/<str:in_region>/ct/create/new/', city_create, name="city-create"),
	path('<int:in_project>/ct/<str:name>/update/', city_update, name="city-update"),
	path('<int:in_project>/ct/<str:name>/delete/', city_delete, name="city-delete"),

	# City Quarters
	path('<int:in_project>/c/<str:in_city>/cq/create/new/', cityquarter_create, name="cityquarter-create"),
	path('<int:in_project>/cq/<str:name>/update/', cityquarter_update, name="cityquarter-update"),
	path('<int:in_project>/cq/<str:name>/delete/', cityquarter_delete, name="cityquarter-delete"),

	# City Demographics
	path('<int:in_project>/ct/<str:in_city>/ctd/create/new/', citydemographics_create, name="citydemographics-create"),
	path('<int:in_project>/ctd/<int:pk>/delete/', citydemographics_delete, name="citydemographics-delete"),

	# Locations
	path('<int:in_project>/a/<str:in_area>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/cq/<str:in_cityquarter>/l/create/new/', location_create, name="location-create"),
	path('<int:in_project>/l/<str:name>/update/', location_update, name="location-update"),
	path('<int:in_project>/l/<str:name>/delete/', location_delete, name="location-delete"),

	# Location Loot
	path('<int:in_project>/l/<str:in_location>/ll/create/new/', locationloot_create, name="locationloot-create"),
	path('<int:in_project>/ll/<int:pk>/delete/', locationloot_delete, name="locationloot-delete"),

	# World Encounter
	path('<int:in_project>/rm/<str:in_dungeon_room>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/l/<str:in_location>/we/create/new/', worldencounter_create, name="worldencounter-create"),
	path('<int:in_project>/we/<str:title>/update/', worldencounter_update, name="worldencounter-update"),
	path('<int:in_project>/we/<str:title>/delete/', worldencounter_delete, name="worldencounter-delete"),

	# World Encounter Loot
	path('<int:in_project>/we/<str:in_worldencounter>/wel/create/new/', worldencounterloot_create, name="worldencounterloot-create"),
	path('<int:in_project>/wel/<int:pk>/delete/', worldencounterloot_delete, name="worldencounterloot-delete"),

	# Empires
	path('<int:in_project>/u/<str:in_universe>/e/create/new/', empire_create, name="empire-create"),
	path('<int:in_project>/e/<str:name>/update/', empire_update, name="empire-update"),
	path('<int:in_project>/e/<str:name>/delete/', empire_delete, name="empire-delete"),

	# Factions
	path('<int:in_project>/u/<str:in_universe>/f/create/new/', faction_create, name="faction-create"),
	path('<int:in_project>/f/<str:name>/update/', faction_update, name="faction-update"),
	path('<int:in_project>/f/<str:name>/delete/', faction_delete, name="faction-delete"),

	# NPCs
	path('<int:in_project>/u/<str:in_universe>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/u/<str:in_universe>/f/<str:in_faction>/n/create/new/', npc_create, name="npc-create"),
	path('<int:in_project>/f/<str:in_faction>/n/<str:name>/update/', npc_update, name="npc-update"),
	path('<int:in_project>/n/<str:name>/delete/', npc_delete, name="npc-delete"),
]

Dungeon/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from ItemList.models import Item
from World.models import Area
from Project.models import Project

class Dungeon(models.Model):
	"""A dungeon is a collection of rooms of varying sizes. These rooms form
	Roomsets."""

	title = models.CharField(max_length=125)
	landscape = models.URLField(max_length=255, blank=True, null=True, help_text="Provide a URL to an image file.")
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_area = models.ForeignKey(Area, on_delete=models.CASCADE)

	description = models.TextField(blank=True, null=True)


	def get_absolute_url(self):
		return reverse('dungeon-detail', args=[str(self.in_project.id), str(self.title)])

	def __str__(self):
		return self.title

class Roomset(models.Model):
	"""A Roomset is a series of adjacent rooms that share an aesthetic theme.
	Typically, a dungeon will have a few Roomsets, represented by levels of a
	dungeon, or different locales."""

	name = models.CharField(max_length=75)
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_dungeon = models.ForeignKey(Dungeon, on_delete=models.CASCADE)

	description = models.TextField(blank=True, null=True)
	# map = 'path/to/file'

	def get_absolute_url(self):
		return reverse('roomset-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class Room(models.Model):
	"""A room typically contains grid-based encounters. This is the layer with
	which the players will interact, and therefore has flavor text."""

	name = models.CharField(max_length=75)
	room_number = models.IntegerField()
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_roomset = models.ForeignKey(Roomset, on_delete=models.CASCADE)
	exits = models.ManyToManyField('Room', blank=True)

	description = models.TextField(blank=True, null=True)

	flavor_text = models.TextField(blank=True, null=True)

	class Meta:
		ordering = ['in_roomset', 'room_number', ]

	def get_absolute_url(self):
		return reverse('room-detail', args=[str(self.in_project.id), str(self.name)])

	def __str__(self):
		return self.name

class RoomLoot(models.Model):
	name = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	in_project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
	in_room = models.ForeignKey(Room, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "Room Loot"

	def __str__(self):
		return self.name.name

Dungeon/forms.py
from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Row
from crispy_forms.bootstrap import InlineCheckboxes

from Dungeon.models import Dungeon, Roomset, Room, RoomLoot

class DungeonModelForm(ModelForm):
	class Meta:
		model = Dungeon
		fields = '__all__'

	def clean_title(self):
		data = self.cleaned_data['title']
		if '/' in data:
			msg = "'/' is not a valid character."
			raise forms.ValidationError(msg)
		if not self.instance.title == data:
			if self.dungeons.filter(title=data).exists():
				msg = "%s already exists in this project." % data
				raise forms.ValidationError(msg)

		return data

	def __init__(self, dungeons, *args, **kwargs):
		super(DungeonModelForm, self).__init__(*args, **kwargs)
		self.dungeons = dungeons
		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Field('title'),
			Field('landscape'),
			Field('description', id="textarea"),
			Field('in_project', type="hidden"),
			Field('in_area', type="hidden"),
		)

class RoomsetModelForm(ModelForm):
	class Meta:
		model = Roomset
		fields = '__all__'

	def clean_name(self):
		data = self.cleaned_data['name']
		if '/' in data:
			msg = "'/' is not a valid character."
			raise forms.ValidationError(msg)
		if not self.instance.name == data:
			if self.roomsets.filter(name=data).exists():
				msg = "%s already exists in this project." % data
				raise forms.ValidationError(msg)
		return data

	def __init__(self, roomsets, *args, **kwargs):
		super(RoomsetModelForm, self).__init__(*args, **kwargs)
		self.roomsets = roomsets

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Field('name'),
			Field('description', id="textarea"),
			Field('in_project', type="hidden"),
			Field('in_dungeon', type="hidden"),
		)

class RoomModelForm(ModelForm):
	class Meta:
		model = Room
		fields = '__all__'

	def clean_name(self):
		data = self.cleaned_data['name']
		if '/' in data:
			msg = "'/' is not a valid character."
			raise forms.ValidationError(msg)
		if not self.instance.name == data:
			if self.rooms.filter(name=data).exists():
				msg = "%s already exists in this project." % data
				raise forms.ValidationError(msg)
		return data

	def __init__(self, room_exits, rooms, *args, **kwargs):
		super(RoomModelForm, self).__init__(*args, **kwargs)
		self.rooms = rooms
		self.fields['exits'].queryset = room_exits

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Field('name'),
			Field('room_number'),
			Field('description', id="textarea"),
			Field('flavor_text'),
			InlineCheckboxes('exits'),
			Field('in_project', type="hidden"),
			Field('in_roomset', type="hidden"),
		)

class RoomLootModelForm(ModelForm):
	class Meta:
		model = RoomLoot
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		self.items = kwargs.pop('items')
		super(RoomLootModelForm, self).__init__(*args, **kwargs)
		self.fields['name'].queryset = self.items

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', 'Create', css_class="btn-success float-right"))

		self.helper.layout = Layout(
			Row(
				Field('name', wrapper_class="col-md-6"),
				Field('quantity', wrapper_class="col-md-6"),
				Field('in_project', type="hidden"),
				Field('in_room', type="hidden")
			)
		)

Dungeon/templates/Dungeon/dungeon_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ dungeon }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Dungeon/templates/Dungeon/dungeon_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ dungeon.title }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ dungeon.title }}</h1>
    <a title="Edit" href="{% url 'dungeon-update' in_project=dungeon.in_project.id title=dungeon.title %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'dungeon-delete' in_project=dungeon.in_project.id title=dungeon.title %}">
      <i class="cil-x"></i>
    </a>
  </div>

  <hr class="page-title-hr">

  <p>{{ dungeon.description }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th colspan="2" class="sidebar-table">{{ dungeon.title }}</th>
      </tr>
    </thead>
    <tbody>
      {% if dungeon.landscape %}
      <td colspan="2">
        <img id="image" src="{{ dungeon.landscape }}" class="img-fluid mx-auto d-block">
        <div id="imageModal" class="modal">
          <span class="close">&times;</span>
          <img class="modal-content" id="modalImage">
        </div>
      </td>
      {% endif %}
    </tbody>
    <tr>
      <th>Area</th>
      <td><a href="{{ dungeon.in_area.get_absolute_url }}">{{ dungeon.in_area }}</a></td>
    </tr>
  </table>

  <div class="table-title">
    <h4>Roomsets</h4>
    <a href="{% url 'roomset-create' in_project=dungeon.in_project.id in_dungeon=dungeon.title %}">
      <i class="cil-plus"></i>
    </a>
  </div>

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Roomset</th>
        <th>Rooms</th>
      </tr>
    </thead>
    <tbody>
    {% for roomset in dungeon.roomset_set.all %}
      <tr>
        <td><a href="{{ roomset.get_absolute_url }}">{{ roomset.name }}</a></td>
        <td>{{ roomset.room_set.all.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

{% block additionalscripts %}
  {% load static %}
  <script type="text/javascript" src="{% static 'js/imagemodals.js' %}"></script>
{% endblock additionalscripts %}

Dungeon/templates/Dungeon/dungeon_form.html
{% extends "base_generic.html" %}

{% block additionalstatic %}
  <script src="https://cdn.tiny.cloud/1/2gcz381i62l40q1b09f9459xib3itxlfnxcb70ye30po1t96/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  {% load static %}
  <script src="{% static 'js/tinymce_config.js' %}"></script>
{% endblock additionalstatic %}

{% block content %}
  
  <h1 class="page-title">Add/Edit Dungeon</h1>
  <hr class="page-title-hr">
   
  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}

Dungeon/templates/Dungeon/room_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ room }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Dungeon/templates/Dungeon/room_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ room.name }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ room.name }}</h1>
    <a title="Edit" href="{% url 'room-update' in_project=room.in_project.id name=room.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a href="{% url 'room-delete' in_project=room.in_project.id name=room.name %}">
      <i class="cil-x"></i>
    </a>
  </div>

  <hr class="page-title-hr">

  <div class="row">
    <div class="col-2">
    </div> <!-- col-2 -->
    <div class="col">
      <p class="flavor-text">{{ room.flavor_text }}</p>
    </div> <!-- col -->
    <div class="col-2">
    </div> <!-- col-2 -->
  </div> <!-- row -->

  <hr class="page-title-hr">

  <p>{{ room.description }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th colspan="2" class="sidebar-table">{{ room.name }}</th>
      </tr>
    </thead>
    <tr>
      <th>Dungeon</th>
      <td><a href="{{ room.in_roomset.in_dungeon.get_absolute_url }}">{{ room.in_roomset.in_dungeon }}</a></td>
    </tr>
    <tr>
      <th>Roomset</th>
      <td>
        <a href="{{ room.in_roomset.get_absolute_url }}">{{ room.in_roomset }}</a>
      </td>
    </tr>
    <tr>
      <th>Quests</th>
      <td>
        <ul>
        {% for encounter in room.encounter_set.all %}
          <li><a href="{{ encounter.in_questlink.get_absolute_url }}">{{ encounter.in_questlink }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Exits</th>
      <td>
        <ul>
        {% for exit in room.exits.all %}
          <li><a href="{{ exit.get_absolute_url }}">{{ exit.name }}</a></li>
        {% endfor %}
        </ul>
      </td>
    </tr>
    <tr>
      <th>Loot
        <a title="Add" href="{% url 'roomloot-create' in_project=room.in_project.id in_room=room.name %}">
          <i class="cil-plus table-icon"></i>
        </a>
      </th>
      <td>
        <ul>
        {% for loot in room.roomloot_set.all %}
          <li>
            <a href="{{ loot.name.get_absolute_url }}">{{ loot.name }}</a> ({{ loot.quantity }}x)
              <a href="{% url 'roomloot-delete' in_project=loot.in_project.id pk=loot.pk %}">
                <i class="cil-x table-icon"></i>
              </a>
          </li>
        {% endfor %}
        <ul>
      </td>
    </tr>
  </table>

  <div class="table-title">
    <h4>Encounters (World)</h4>
    <a title="Add" href="{% url 'worldencounter-create' in_project=room.in_project.id in_dungeon_room=room.name %}">
      <i class="cil-plus"></i>
    </a>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Encounter Title</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
    {% for encounter in room.worldencounter_set.all %}
    <tr>
      <td>{{ encounter.encounter_num }}</td>
      <td><a href="{{ encounter.get_absolute_url }}">{{ encounter.title }}</a></td>
      <td>{{ encounter.get_encounter_type_display }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

  {% if room.questencounter_set.count > 0 %}
  <div class="table-title">
    <h4>Encounters (Quest)</h4>
  </div> <!-- table-title -->

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Encounter Title</th>
        <th>Type</th>
        <th>Quest</th>
      </tr>
    </thead>
    <tbody>
    {% for encounter in room.questencounter_set.all %}
    <tr>
      <td>{{ encounter.encounter_num }}</td>
      <td><a href="{{ encounter.get_absolute_url }}">{{ encounter.title }}</a></td>
      <td>{{ encounter.get_encounter_type_display }}</td>
      <td><a href="{{ encounter.in_quest.get_absolute_url }}">{{ encounter.in_quest }}</a></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock rightsidebar %}

Dungeon/templates/Dungeon/room_form.html
{% extends "base_generic.html" %}

{% block additionalstatic %}
  <script src="https://cdn.tiny.cloud/1/2gcz381i62l40q1b09f9459xib3itxlfnxcb70ye30po1t96/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  {% load static %}
  <script src="{% static 'js/tinymce_config.js' %}"></script>
{% endblock additionalstatic %}

{% block content %}
  
  <h1 class="page-title">Add/Edit Room</h1>
  <hr class="page-title-hr">
   
  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}

Dungeon/templates/Dungeon/roomloot_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete: {{ roomloot }} ({{ roomloot.quantity}}x)?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Dungeon/templates/Dungeon/roomloot_form.html
{% extends "base_generic.html" %}

{% block content %}

  <h1 class="page-title">Add Loot</h1>
  <hr class="page-title-hr">

  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}

Dungeon/templates/Dungeon/roomset_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  
  <p>Are you sure you want to delete {{ roomset }}?</p>
  
  <input class="btn btn-secondary" type="submit" value="Back" onclick="window.history.go(-1)">
  <input class="btn btn-danger" type="submit" value="Delete">
</form>
{% endblock content %}

Dungeon/templates/Dungeon/roomset_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ roomset.name }}</title>
{% endblock title %}

{% block content %}
  <div class="page-title">
    <h1>{{ roomset.name }}</h1>
    <a title="Edit" href="{% url 'roomset-update' in_project=roomset.in_project.id name=roomset.name %}">
      <i class="cil-pencil"></i>
    </a>
    <a title="Delete" href="{% url 'roomset-delete' in_project=roomset.in_project.id name=roomset.name %}">
      <i class="cil-x"></i>
    </a>
  </div>

  <hr class="page-title-hr">

  <p>{{ roomset.description }}</p>

{% endblock content %}

{% block rightsidebar %}
  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th colspan="2" class="sidebar-table">{{ roomset.name }}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>Dungeon</th>
        <td><a href="{{ roomset.in_dungeon.get_absolute_url }}">{{ roomset.in_dungeon }}</a></td>
      </tr>
    </tbody>
  </table>

  <div class="table-title">
    <h4>Rooms</h4>
    <a href="{% url 'room-create' in_project=roomset.in_project.id in_roomset=roomset.name %}">
      <i class="cil-plus"></i>
    </a>
  </div>

  <table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Encounters</th>
      </tr>
    </thead>
    <tbody>
    {% for room in roomset.room_set.all %}
      <tr>
        <td>{{ room.room_number }}</td>
        <td><a href="{{ room.get_absolute_url }}">{{ room.name }}</a></td>
        <td>
          {{ room.worldencounter_set.count|add:room.questencounter_set.count }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock rightsidebar %}

Dungeon/templates/Dungeon/roomset_form.html
{% extends "base_generic.html" %}

{% block additionalstatic %}
  <script src="https://cdn.tiny.cloud/1/2gcz381i62l40q1b09f9459xib3itxlfnxcb70ye30po1t96/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  {% load static %}
  <script src="{% static 'js/tinymce_config.js' %}"></script>
{% endblock additionalstatic %}

{% block content %}
  
  <h1 class="page-title">Add/Edit Roomset</h1>
  <hr class="page-title-hr">
   
  {% csrf_token %}
  {% load crispy_forms_tags %}
  {% crispy form form.helper %}

{% endblock content %}